version: '3.8'
services:
  zookeeper:
    image: wurstmeister/zookeeper:3.4.6
    restart: always
    ports:
      - "127.0.0.1:2181:2181"

  kafka:
    depends_on:
      - zookeeper
    image: wurstmeister/kafka:2.13-2.8.1
    restart: always
    environment:
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_ADVERTISED_HOST_NAME=localhost
      - KAFKA_ADVERTISED_PORT=9092
      - KAFKA_CREATE_TOPICS=topic.example:1:1
    ports:
      - "127.0.0.1:9092:9092"

